engines:
  watson:
    enabled: true
  scss-lint:
    enabled: true
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - app/**
exclude_paths:
- "app/mirage/*"
- "app/templates/*"
