scss_files: 'app/styles/**/*.scss'

linters:
  NestingDepth:
    enabled: true
    max_depth: 4
  SelectorDepth:
    enabled: true
    max_depth: 4
  Comment:
    allowed: '^[/*]*'
  QualifyingElement:
    allow_element_with_attribute: true
