---
language: node_js

sudo: true

env:
  global:
    #set these here becuase they get pullout by testem saucie
    - SAUCE_USERNAME="ilios"
    - SAUCE_ACCESS_KEY="e7c24f1d-ec10-435d-9cec-d1c38bafa268"
addons:
  hosts:
    - localtest

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - sudo apt-get update -qq
  # install netstat
  - sudo apt-get install net-tools

install:
  - npm install -g bower
  - npm install -g saucie
  - npm install
  - bower install

before_script:
  # Start a server so we can hit the fake API from integration tests
  - ember s --live-reload=false &
  # wait for the server to be started
  - until netstat -an 2>/dev/null | grep '4200.*LISTEN'; do true; done

script:
  - ember test --config-file=testemci.json --port=8080 --host=localtest --env=citests

#encrypted the IRC room chat.freenode.net##ilios so that it doesn't run on pull requests
notifications:
  irc:
    secure: CNNvi0C+FdiVIEXJmiF0QbpsJPkjV4r83EFUhJepvk8t2kRDMFg1ya+mZinGZ8s0Wgi9d6vsu9+2deb82va59reM/lqItj+oSYEHpW9zq6QZUJ27guyAFzqCKW1JuyPQB0SQ74Jh/jD+iAAj+ho/5Y/3I+0fNaq6+yi6RrI0VeA=
