---
#really we're using node_js but this works with the osx OS
language: objective-c
#we use OSX here because phantomJS2 isn't super stable on Linux
os: osx
sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 0.12.7
  - npm config set spin false
  - npm install -g npm@^2
  - npm install -g phantomjs2
  - npm install -g bower
  - travis_retry gem install scss-lint --no-ri --no-rdoc

install:
  - travis_retry npm install --no-optional
  - travis_retry bower install

script:
  - scss-lint
  - node_modules/.bin/ember test --launch=PhantomJS

#encrypted the slack token to post to #info so that it doesn't run on pull requests or forks
notifications:
    slack:
      secure: oloxDKdwXmNHKhh5WSR8DDxA3WJdAnyj+vj/8yawF1zG0tgL4fyPzzFqSpEhfsfgBrJlvxFtSnnsWEIMSMdT1LTwReClyjsy3PFQnHIiLMv/IZUS7ijahXQ4XL+ejfyPV4rJtFuKOLuNMww8uniy705/QkqBYwFUAcXXQ3gV5V8=
