---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    #set these here becuase they get pulled out by testem saucie
    - SAUCE_USERNAME="ilios"
    - SAUCE_ACCESS_KEY="e7c24f1d-ec10-435d-9cec-d1c38bafa268"
    - START_SAUCE_CONNECT=false
    - JS_TESTS=true
    - SCSS_LINT=false
    - TESTEM_LAUNCHER='PhantomJS'
    - SEND_COVERAGE=true

matrix:
  fast_finish: true
  allow_failures:
  include:
    - env: "TESTEM_LAUNCHER='SL_chrome' START_SAUCE_CONNECT=true JS_TESTS=true SEND_COVERAGE=false"
    - env: "JS_TESTS=false SCSS_LINT=true SEND_COVERAGE=false"


before_install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - if [ "$JS_TESTS" = true ]; then npm install -g bower; fi
  - if [ "$JS_TESTS" = true ]; then travis_retry npm install --no-optional; fi
  - if [ "$JS_TESTS" = true ]; then travis_retry bower install; fi
  - if [ "$SCSS_LINT" = true ]; then travis_retry gem install scss-lint; fi

before_script:
  # Create a sauce tunnel
  - if [ "$START_SAUCE_CONNECT" = true ]; then travis_retry ember sauce:connect; fi

script:
  - if [ "$SCSS_LINT" = true ]; then scss-lint; fi
  - if [ "$JS_TESTS" = true ] && [ "$SEND_COVERAGE" = false ]; then travis_wait node_modules/.bin/ember test --launch=${TESTEM_LAUNCHER}; fi
  - if [ "$JS_TESTS" = true ] && [ "$SEND_COVERAGE" = true ]; then travis_wait node_modules/.bin/ember test --test-page='tests/index.html?hidepassed&coverage' --launch=${TESTEM_LAUNCHER}; fi

after_script:
  # Destroy the sauce tunnel
  - if [ "$START_SAUCE_CONNECT" = true ]; then ember sauce:disconnect; fi
  - if [ "$SEND_COVERAGE" = true ]; then CODECLIMATE_REPO_TOKEN=8c510ad3aa4b1a2a3d504dfdbcc5605e7966c019dc1e9b68a815de50b946ebc6 node_modules/.bin/codeclimate-test-reporter < lcov.dat; fi

#encrypted the slack token to post to #info so that it doesn't run on pull requests or forks
notifications:
    slack:
      secure: oloxDKdwXmNHKhh5WSR8DDxA3WJdAnyj+vj/8yawF1zG0tgL4fyPzzFqSpEhfsfgBrJlvxFtSnnsWEIMSMdT1LTwReClyjsy3PFQnHIiLMv/IZUS7ijahXQ4XL+ejfyPV4rJtFuKOLuNMww8uniy705/QkqBYwFUAcXXQ3gV5V8=
