---
#really we're using node_js but this works with the osx OS
language: objective-c
#we use OSX here because phantomJS2 isn't super stable on Linux
os: osx
sudo: false

cache:
  directories:
    - node_modules
    - travis-phantomjs

matrix:
  fast_finish: true

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install v5
  - PHANTOM_DIR=$PWD/../travis-phantom
  - if [ ! -d $PHANTOM_DIR ]; then wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip -O phantomjs.zip; fi
  - if [ ! -d $PHANTOM_DIR ]; then unzip phantomjs.zip; fi
  - if [ ! -d $PHANTOM_DIR ]; then mv phantomjs-2.0.0-macosx $PHANTOM_DIR; fi
  - export PATH=$PHANTOM_DIR/bin:$PATH
  - phantomjs -v
  - npm set progress=false
  - npm config set spin false
  - npm install -g bower
  - travis_retry gem install scss-lint --no-ri --no-rdoc

install:
  - travis_retry npm install --no-optional
  - travis_retry bower install

script:
  - scss-lint
  - npm test

#encrypted the slack token to post to #info so that it doesn't run on pull requests or forks
notifications:
    slack:
      secure: oloxDKdwXmNHKhh5WSR8DDxA3WJdAnyj+vj/8yawF1zG0tgL4fyPzzFqSpEhfsfgBrJlvxFtSnnsWEIMSMdT1LTwReClyjsy3PFQnHIiLMv/IZUS7ijahXQ4XL+ejfyPV4rJtFuKOLuNMww8uniy705/QkqBYwFUAcXXQ3gV5V8=
