---
dist: trusty
language: node_js
node_js: 6
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/bower

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn
  - bower install

script: ember exam --split=$SPLIT --partition=$PARTITION --filter=$FILTER --parallel=$PARALLEL

jobs:
  include:
    - stage: prepare
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
      script: true
    - stage: test
      env: PARTITION=false FILTER='!acceptance' SPLIT=4 PARALLEL=true
    - stage: test
      env: PARTITION=1 FILTER='acceptance' SPLIT=4 PARALLEL=false
    - stage: test
      env: PARTITION=2 FILTER='acceptance' SPLIT=4 PARALLEL=false
    - stage: test
      env: PARTITION=3 FILTER='acceptance' SPLIT=4 PARALLEL=false
    - stage: test
      env: PARTITION=4 FILTER='acceptance' SPLIT=4 PARALLEL=false
    - stage: deploy staging
      if: branch = master AND NOT type = pull_request
      script: node_modules/.bin/ember deploy staging --activate
    - stage: deploy production
      if: tag IS present
      script: node_modules/.bin/ember deploy production --activate
